---
- name: Ensure that conf.d directory exists
  file: path=/etc/nginx/conf.d state=directory

- name: create directory /var/www
  file: path=/var/www state=directory

- name: copy over local.html
  template: src=templates/local.html.j2 dest=/var/www/local.html

- name: copy over on-call-schedule.html
  template: src=templates/on-call-schedule.html.j2 dest=/var/www/on-call-schedule.html

- name: Update nginx.conf
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: setup default.conf - as asked in the task
  template: src=templates/default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify:
    - reload nginx
...
